#!/system/bin/sh
# This self destructs on first boot

# SQLite Vacuuming
for i in \
`busybox find /data -iname "*.db"`; 
do \
	sqlite3 $i 'VACUUM;'; 
	sqlite3 $i 'REINDEX;'; 
done;

if [ -d "/dbdata" ]; then
	for i in \
	`busybox find /dbdata -iname "*.db"`; 
	do \
		sqlite3 $i 'VACUUM;'; 
		sqlite3 $i 'REINDEX;'; 
	done;
fi;


if [ -d "/datadata" ]; then
	for i in \
	`busybox find /datadata -iname "*.db"`; 
	do \
		sqlite3 $i 'VACUUM;'; 
		sqlite3 $i 'REINDEX;'; 
	done;
fi;


for i in \
`busybox find /sdcard -iname "*.db"`; 
do \
	sqlite3 $i 'VACUUM;'; 
	sqlite3 $i 'REINDEX;'; 
done;

sysrw

# Nuking run once scripts
rm /system/etc/init.d/01cherrybomb


sysro
