#!/system/bin/sh
# Franco-c

sync
sysrw

# etc
echo "0" >/proc/sys/net/ipv6/conf/all/forwarding
renice -17 `pidof com.android.systemui`
echo "0" > /proc/sys/net/ipv4/tcp_timestamps
echo "1" > /proc/sys/net/ipv4/tcp_no_metrics_save
echo "0" > /proc/sys/net/ipv4/tcp_timestamps;
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;

# Enable Sysctl Tweaks
sysctl -p /system/etc/sysctl.conf

# Breaking the lease
echo "15" > /proc/sys/fs/lease-break-time

sync
sysro
