#!/system/bin/sh
# Franco-c

sync
sysrw

# etc
echo "0" >/proc/sys/net/ipv6/conf/all/forwarding
renice -17 `pidof com.android.systemui`
echo "0" > /proc/sys/net/ipv4/tcp_timestamps
echo "1" > /proc/sys/net/ipv4/tcp_no_metrics_save
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
echo "1" > /proc/sys/net/ipv4/tcp_sack;
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;

MTD=`ls -d /sys/block/mtd*`;
LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;

for j in $DM $MTD $LOOP $RAM;
do
echo "0" > $j/queue/rotational;
done;

busybox mount -o remount,noauto_da_alloc,nosuid,nodev,noatime,nodiratime /data /data
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /cache

# Enable Sysctl Tweaks
sysctl -p /system/etc/sysctl.conf

# Set SD Card Cache
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb;

# Breaking the lease
echo "15" > /proc/sys/fs/lease-break-time

sync
sysro
